# Generated by Django 5.2.7 on 2025-10-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_billing_address_data',
            field=models.JSONField(blank=True, help_text='Billing address for guest orders', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email for guest orders', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='Phone for guest orders', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_shipping_address_data',
            field=models.JSONField(blank=True, help_text='Shipping address for guest orders', null=True),
        ),
    ]
