# Generated by Django 5.2.7 on 2025-10-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_default_address_per_user',
        ),
    ]
