# Generated by Django 5.2.7 on 2025-10-20 10:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading text for the banner', max_length=200, verbose_name='Banner Title')),
                ('subtitle', models.CharField(blank=True, help_text='Optional descriptive text or tagline', max_length=300, verbose_name='Banner Subtitle')),
                ('image', models.ImageField(help_text='Main banner image for desktop view', upload_to='banners/%Y/%m/', verbose_name='Banner Image')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile-optimized banner image (uses main image if not provided)', null=True, upload_to='banners/%Y/%m/mobile/', verbose_name='Mobile Banner Image')),
                ('button_text', models.CharField(default='Shop Now', help_text='Text displayed on the call-to-action button', max_length=50, verbose_name='Button Text')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first (0 = highest priority)', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive banners are not displayed on the site', verbose_name='Active Status')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional: Banner will only display after this date/time', null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional: Banner will stop displaying after this date/time', null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('link_product', models.ForeignKey(blank=True, help_text='Product to link to when banner is clicked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.product', verbose_name='Linked Product')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Heading text for the product section', max_length=200, verbose_name='Section Title')),
                ('subtitle', models.CharField(blank=True, help_text='Optional descriptive text for the section', max_length=300, verbose_name='Section Subtitle')),
                ('section_type', models.CharField(choices=[('manual', 'Manual Selection'), ('new', 'New Arrivals'), ('featured', 'Featured Products'), ('sale', 'On Sale'), ('category', 'From Category')], default='manual', help_text='How products are selected for this section', max_length=20, verbose_name='Section Type')),
                ('max_products', models.IntegerField(default=8, help_text='Maximum number of products to display (1-50)', validators=[django.core.validators.MinValueValidator(1, message='Must display at least 1 product'), django.core.validators.MaxValueValidator(50, message='Cannot display more than 50 products')], verbose_name='Maximum Products')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first on the homepage', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sections are not displayed on the homepage', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, help_text='Required when section type is "From Category"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_sections', to='catalog.category', verbose_name='Category')),
                ('products', models.ManyToManyField(blank=True, help_text='Select products manually (only used for "Manual Selection" type)', related_name='featured_in_sections', to='catalog.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Featured Section',
                'verbose_name_plural': 'Featured Sections',
                'db_table': 'featured_sections',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
