# Generated by Django 5.2.7 on 2026-01-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredsection',
            name='category',
        ),
        migrations.AlterField(
            model_name='featuredsection',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select products to display in this section', related_name='featured_in_sections', to='catalog.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='featuredsection',
            name='section_type',
            field=models.CharField(choices=[('new', 'New Arrivals'), ('featured', 'Featured Products'), ('sale', 'On Sale'), ('popular', 'Popular Products'), ('custom', 'Custom Section')], default='featured', help_text='Label/category for this section (for organization purposes)', max_length=20, verbose_name='Section Type'),
        ),
    ]
