# Generated by Django 5.2.7 on 2025-10-13 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., Color, Size, Material', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name', unique=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which attributes are shown')),
            ],
            options={
                'verbose_name': 'Attribute Type',
                'verbose_name_plural': 'Attribute Types',
                'db_table': 'attribute_types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Brand Name')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brand description')),
                ('logo', models.ImageField(blank=True, help_text='Brand logo', null=True, upload_to='brands/')),
                ('website', models.URLField(blank=True, help_text='Brand website URL')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive brands are hidden from storefront')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='E.g., Red, Blue, Medium', max_length=200)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which values are shown')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attributetype')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'verbose_name_plural': 'Attribute Values',
                'db_table': 'attribute_values',
                'ordering': ['attribute_type', 'display_order', 'value'],
                'unique_together': {('attribute_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Leave empty for top-level category')),
                ('image', models.ImageField(blank=True, help_text='Category banner image', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden from storefront')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for top-level category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Product Title')),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base/starting price (variants may differ)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Product Price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sale Price')),
                ('stock', models.IntegerField(default=0, help_text='Total stock across all variants (informational only)', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alert when stock falls below this number')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive products are hidden from storefront')),
                ('meta_title', models.CharField(blank=True, help_text='SEO page title', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product image', upload_to='products/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('position', models.IntegerField(default=0, help_text='Display order (0 = primary image)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'db_table': 'product_images',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Unique identifier for the variant', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the variant', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price of the variant', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available stock for the variant')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive variants are hidden from storefront')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'ordering': ['product', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attributevalue')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Attribute',
                'verbose_name_plural': 'Variant Attributes',
                'db_table': 'variant_attributes',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='products_is_acti_b753ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantattribute',
            unique_together={('product_variant', 'attribute_value')},
        ),
    ]
